#!/bin/bash

bin_destination=$1
lib_destination=$2
includes_destination=$3

if [ ! -d $bin_destination ]; then
    mkdir -p $bin_destination
    echo "Created directory bin_destination"
fi

if [ ! -d $lib_destination ]; then
    mkdir -p $lib_destination
    echo "Created directory $lib_destination"
fi

if [ ! -d $lib_destination ]; then
    mkdir -p $lib_destination
    echo "Created directory $lib_destination"
fi

# install libraries
cp linux/lib*.so ${lib_destination}


# install binaries
cp linux/benchClient linux/benchServer linux/checkDimServers linux/checkDns linux/did linux/DimBridge \
	linux/dim_get_service linux/dim_send_command linux/dns linux/rpcClient linux/rpcServer linux/test_client \
	linux/test_server linux/testServer linux/webDid \
	${bin_destination}

# install includes
cp dim/*.hxx dim/*.h ${includes_destination}